#
name: Create and publish hybrid-runtime binaries

# Configures this workflow to run every time a release is created
on:
 release:
    types: [published]

#push:
#    branches: ['main']



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
          file: docker/runtime.dockerfile
          push: false          
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a          
