#
name: Create and publish hybrid-runtime binaries

# Configures this workflow to run every time a release is created
on:
 release:
    types: [published]

#push:
#    branches: ['main']

jobs:
  build3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          file: docker/runtime.dockerfile
          tags: myimage:latest
          push: false          
          load: true

#
#      - name: Checkout repository
#        uses: actions/checkout@v4
# 
#      - name: build binary
#        uses: addnab/docker-run-action@v3
#        with:
#          image: myimage:latest
#          options: -v ${{ github.workspace }}:/runtime -w /runtime/runtime/shim          
#          run: |
#             cargo build --target aarch64-unknown-linux-musl
#             ls -l /runtime/runtime/shim/target/
# 

      - name: build binary
        uses: addnab/docker-run-action@v3
        with:
          image: myimage:latest
          options: -v ${{ github.workspace }}:/runtime -w /runtime/runtime/runtime
          run: |
            cargo build --target aarch64-unknown-linux-musl
            ls -l /runtime
            ls -l /runtime/runtime


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hybrid
          path: |
              ${{ github.workspace }}/runtime/shim/target/aarch64-unknown-linux-musl/debug/containerd-shim-containerd-hybrid
              ${{ github.workspace }}/runtime/runtime/target/aarch64-unknown-linux-musl/debug/hybrid-cli
              ${{ github.workspace }}/runtime/pause.sh
              ${{ github.workspace }}/runtime/resize.sh     

